### ISSUE TITLE
Syntax error ...

### ISSUE THREAD

**Issue by imcom** [jeffjose/tget#4]
`
root@localhost:~# tget

/usr/local/lib/node_modules/t-get/node_modules/parse-torrent/node_modules/simple-get/node_modules/unzip-response/index.js:2
const PassThrough = require('stream').PassThrough;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/t-get/node_modules/parse-torrent/node_modules/simple-get/index.js:8:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
`

Hi, you got any idea on how is this ?

**Comment by imcom** [comment]
upgrade nodejs to latest version fixed the issue ...
