### ISSUE TITLE
cannot run tget

### ISSUE THREAD

**Issue by zhangxulong** [jeffjose/tget#5]
/usr/local/lib/node_modules/t-get/node_modules/parse-torrent/index.js:110
;(function () { Buffer.alloc(0) })()
                       ^

TypeError: Buffer.alloc is not a function
    at /usr/local/lib/node_modules/t-get/node_modules/parse-torrent/index.js:110:24
    at Object.<anonymous> (/usr/local/lib/node_modules/t-get/node_modules/parse-torrent/index.js:110:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/t-get/app.js:9:21)
    at Module._compile (module.js:410:26)

**Comment by ice1000** [comment]
Same here

**Comment by f97-2308** [comment]
Me too... :+1:

**Comment by zyt312074545** [comment]
@zhangxulong @ice1000 @huynhduckhoan 
You need upgrade the node version.
`sudo n stable`
When I upgrade the node version, it is usable.
